- src/main/java/com/campick/server/api/car/entity/Car.java
- src/main/java/com/campick/server/api/car/repository/CarRepository.java
- src/main/java/com/campick/server/api/car/service/CarService.java
- src/main/java/com/campick/server/api/chat/entity/ChatMessage.java
- src/main/java/com/campick/server/api/chat/entity/ChatRoom.java
- src/main/java/com/campick/server/api/dealer/entity/Dealer.java
- src/main/java/com/campick/server/api/engine/entity/Engine.java
- src/main/java/com/campick/server/api/engine/entity/FuelType.java
- src/main/java/com/campick/server/api/engine/entity/Transmission.java
- src/main/java/com/campick/server/api/favorite/entity/Favorite.java
- src/main/java/com/campick/server/api/member/controller/MemberController.java
- src/main/java/com/campick/server/api/member/dto/MemberResponseDto.java
- src/main/java/com/campick/server/api/member/dto/MemberSignUpRequestDto.java
- src/main/java/com/campick/server/api/member/entity/Member.java
- src/main/java/com/campick/server/api/member/entity/Role.java
- src/main/java/com/campick/server/api/member/repository/MemberRepository.java
- src/main/java/com/campick/server/api/member/service/MemberService.java
- src/main/java/com/campick/server/api/model/entity/Model.java
- src/main/java/com/campick/server/api/option/entity/Option.java
- src/main/java/com/campick/server/api/option/entity/ProductionOption.java
- src/main/java/com/campick/server/api/product/entity/Product.java
- src/main/java/com/campick/server/api/product/entity/ProductImage.java
- src/main/java/com/campick/server/api/product/entity/ProductStatus.java
- src/main/java/com/campick/server/api/product/entity/ProductType.java
- src/main/java/com/campick/server/api/review/entity/Review.java
- src/main/java/com/campick/server/api/type/entity/Type.java
- src/main/java/com/campick/server/api/type/entity/VehicleTypeName.java
- close #6 
- CloudERD 기준으로 기본적인 엔티티를 구현했습니다
- 수정하실 것은 편히 수정해주세요!
> Feat/#6 엔티티 초기 구현

- src/main/java/com/campick/server/ServerApplication.java
- src/main/java/com/campick/server/api/member/controller/MemberController.java
- src/main/java/com/campick/server/api/member/dto/EmailVerificationCodeRequestDto.java
- src/main/java/com/campick/server/api/member/dto/EmailVerificationRequestDto.java
- src/main/java/com/campick/server/api/member/dto/MemberLoginRequestDto.java
- src/main/java/com/campick/server/api/member/entity/EmailVerification.java
- src/main/java/com/campick/server/api/member/repository/EmailVerificationRepository.java
- src/main/java/com/campick/server/api/member/repository/MemberRepository.java
- src/main/java/com/campick/server/api/member/service/EmailService.java
- src/main/java/com/campick/server/common/config/mail/MailConfig.java
- src/main/java/com/campick/server/common/entity/BaseTimeEntity.java
- src/main/java/com/campick/server/common/response/ErrorStatus.java
- src/main/java/com/campick/server/common/response/SuccessStatus.java
- src/main/resources/application-local.properties
- src/main/resources/application.properties
> #16 feat/Email: 이메일 인증 구현

- Dockerfile
- build.gradle
- close #22
dockerfile - platform linux 통일
빌드 그래들 - 실행 파일 이름 고정 app.jar
> fix: docker & gradle

- src/main/java/com/campick/server/api/member/service/MemberService.java
- src/main/java/com/campick/server/api/product/dto/AllProductResponseDto.java
- src/main/java/com/campick/server/api/product/service/ProductService.java
- src/main/java/com/campick/server/common/response/SuccessStatus.java
- close #31
- errorStatus user_not_found -> member_not_found로 수정 클래스도 멤버로 돼 있어서 멤버로 바꿨습니다.
- 그리고 매물 조회에서 임시로 생성자 추가=
errorStatus user_not_found -> member_not_found로 수정 클래스도 멤버로 돼 있어서 멤버로 바꿨습니다.
> fix: status

- src/main/java/com/campick/server/common/config/security/SecurityConfig.java
- close #33
products -> product
> fix: securityConfig

- .github/workflows/deploy.yml
- close #37
집에 가기 위한 자동 배포 설정
간단하게 서버 접속해서
풀 하고
도커 업 하는 것으로 설정
> Add GitHub Actions workflow for AWS deployment

- README.md
> #39 feat(CI/CD): 배포 테스트를 위한 README.md 수정

- src/main/java/com/campick/server/api/chat/controller/ChatController.java
- src/main/java/com/campick/server/api/chat/dto/ChatListDto.java
- src/main/java/com/campick/server/api/chat/dto/MyChatResDto.java
- close #55
- 응답 데이터 채팅방 리스트 포함으로 수정
> fix: 내 채팅방 목록 조회

- src/main/java/com/campick/server/common/config/websocket/MemberHandshakeInterceptor.java
- src/main/java/com/campick/server/common/config/websocket/WebSocketConfig.java
- close #58
연결 시 경로에서 유저 아이디 파싱 후 저장
> feat: 인터셉터 설정

- src/main/java/com/campick/server/common/config/websocket/MemberHandshakeInterceptor.java
- src/main/java/com/campick/server/common/config/websocket/WebSocketConfig.java
- #58
/ws -> /ws/**
이걸 왜...
그리고 인터셉터에 디버깅 코드
웹소켓 연결됨
세부 사항은 이후 추가 구현 필요
> fix: websocket config

- src/main/java/com/campick/server/api/chat/service/ChatService.java
- src/main/java/com/campick/server/api/member/controller/MemberController.java
- src/main/java/com/campick/server/api/member/dto/MemberProductListPageDto.java
- src/main/java/com/campick/server/api/member/dto/MemberResponseDto.java
- src/main/java/com/campick/server/api/member/dto/MemberSignUpRequestDto.java
- src/main/java/com/campick/server/api/member/dto/MemberTransactionListPageDto.java
- src/main/java/com/campick/server/api/member/dto/ReviewSummaryDto.java
- src/main/java/com/campick/server/api/member/dto/TransactionResponseDto.java
- src/main/java/com/campick/server/api/member/entity/Member.java
- src/main/java/com/campick/server/api/member/service/MemberService.java
- src/main/java/com/campick/server/api/product/repository/ProductRepository.java
- src/main/java/com/campick/server/api/transaction/repository/TransactionRepository.java
- src/main/java/com/campick/server/common/config/DataInitializer.java
- src/main/java/com/campick/server/common/config/security/SecurityConfig.java
- src/main/java/com/campick/server/common/config/swagger/SwaggerConfig.java
- src/main/java/com/campick/server/common/response/SuccessStatus.java
…션 처리
- close #63 
멤버가 현재 팔고 있는, 팔았던, 샀던 매물 조회 memeberId 기준으로 페이지네이션기능 구현
- @vivivim 멤버의 속성중 profileImage를 profileImageUrl로 바꿨습니다. 사용하는 파일들도 수정했습니다
> #63 멤버 별 매물 조회 기능 수정

- src/main/java/com/campick/server/api/member/controller/MemberController.java
- src/main/java/com/campick/server/api/member/dto/ReviewListPageDto.java
- src/main/java/com/campick/server/api/member/dto/ReviewResponseDto.java
- src/main/java/com/campick/server/api/member/service/MemberService.java
- src/main/java/com/campick/server/api/review/repository/ReviewRepository.java
- src/main/java/com/campick/server/common/response/ErrorStatus.java
- close #69 
- 멤버 ID로 리뷰 확인 가능합니다
> #69/feat 멤버ID로 리뷰 확인 기능 구성

- .github/workflows/close-issue-develop.yml
- .github/workflows/pr.yml
- src/main/java/com/campick/server/api/member/service/MemberService.java
- src/main/java/com/campick/server/api/product/service/ProductService.java
- src/main/resources/application.properties
> #86 fix(RollbackCode) : 삭제된 코드를 복구합니다

- .github/workflows/close-issue-develop.yml
- .github/workflows/pr.yml
- src/main/java/com/campick/server/api/member/service/MemberService.java
- src/main/java/com/campick/server/api/product/service/ProductService.java
- src/main/java/com/campick/server/common/response/ErrorStatus.java
- src/main/resources/application.properties
> Main 브랜치 업데이트

- src/main/java/com/campick/server/api/favorite/repository/FavoriteRepository.java
- src/main/java/com/campick/server/api/product/controller/ProductController.java
- src/main/java/com/campick/server/api/product/dto/StatusReqDto.java
- src/main/java/com/campick/server/api/product/service/ProductService.java
- src/main/java/com/campick/server/common/response/ErrorStatus.java
- src/main/java/com/campick/server/common/response/SuccessStatus.java
> #68/feat like

- .github/workflows/pr.yml
- src/main/resources/application.properties
> Dev 브랜치에 main 브랜치 변경사항 업데이트

- src/main/java/com/campick/server/api/member/controller/MemberController.java
- src/main/java/com/campick/server/api/member/controller/MemberCountController.java
- src/main/java/com/campick/server/api/member/service/CountService.java
- src/main/java/com/campick/server/api/member/service/MemberService.java
- src/main/java/com/campick/server/api/product/repository/ProductRepository.java
- src/main/java/com/campick/server/common/config/security/SecurityConfig.java
- src/main/java/com/campick/server/common/response/SuccessStatus.java
- close #102 
- 멤버가 등록한 매물 개수를 반환 합니다
> #102 feat/MemberProductCount : 멤버가 등록한 매물 개수를 반환

- src/main/java/com/campick/server/api/product/dto/ProductImageUploadResponseDto.java
- src/main/java/com/campick/server/common/config/security/SecurityConfig.java
> #102 fix/ConfigAndDto : 매물 등록시에 썸네일 보내지 않기, 개수 조회 403해결

- src/main/java/com/campick/server/api/member/controller/MemberController.java
- src/main/java/com/campick/server/api/member/dto/MemberPasswordCheckRequestDto.java
- src/main/java/com/campick/server/api/member/service/MemberService.java
- src/main/java/com/campick/server/common/response/SuccessStatus.java
> #112 feat/checkPassword : 로그인 중에 자신의 비밀번호를 체크합니다

- src/main/java/com/campick/server/api/product/service/ProductService.java
> fix: 매물 등록

- src/main/java/com/campick/server/api/car/repository/CarRepository.java
- src/main/java/com/campick/server/api/product/service/ProductService.java
- src/main/java/com/campick/server/common/config/DataInitializer.java
- src/main/java/com/campick/server/common/config/security/SecurityConfig.java
- src/main/java/com/campick/server/common/response/ErrorStatus.java
- src/main/resources/application.properties
- #119
매물 등록 자동차 에러 처리
create 전략으로 수정
> 이거 한번 올려봐도 되겠나요 

- src/main/java/com/campick/server/api/member/dto/ProductAllSummaryDto.java
> #140 fix(MemberProductAll) 속성오류

- .gitignore
- src/main/java/com/campick/server/api/favorite/repository/FavoriteRepository.java
- src/main/java/com/campick/server/api/favorite/service/FavoriteService.java
- src/main/java/com/campick/server/api/member/controller/MemberCountController.java
- src/main/java/com/campick/server/api/member/controller/MemberFavoriteController.java
- src/main/java/com/campick/server/api/member/dto/ProductAvailableSummaryDto.java
- src/main/java/com/campick/server/api/member/dto/TransactionResponseDto.java
- src/main/java/com/campick/server/api/member/service/MemberService.java
- src/main/java/com/campick/server/api/product/dto/ProductResDto.java
- src/main/java/com/campick/server/common/config/security/SecurityConfig.java
- src/main/java/com/campick/server/common/response/SuccessStatus.java
- close #140 
- 아침에 테스트 한번더 해보겠습니다
> Feat/#140 멤버 좋아요 매물과 개수 API
